"""Extract the Joe-Kuo Sobol direction-number table from the Boost header.

Usage: python tools/extract_sobol_table.py [boost_header] [max_dimension]

Writes include/nested_sampler/sobol_table.hpp. The output reproduces the
default table of boost::random::sobol_engine (BSL-1.0 licensed) truncated to
max_dimension dimensions, so that the Sobol sequence generated by this package
is bit-identical to Boost's for those dimensions.
"""
import re
import sys
from pathlib import Path

header = Path(sys.argv[1] if len(sys.argv) > 1 else "/usr/include/boost/random/detail/sobol_table.hpp")
max_dim = int(sys.argv[2]) if len(sys.argv) > 2 else 512
max_degree = 15

text = header.read_text()

def array_body(name):
    m = re.search(name + r"\[[^\]]*\]\s*=\s*\{(.*?)\};", text, re.S)
    body = re.sub(r"//.*", "", m.group(1))
    return [int(v) for v in body.replace("\n", " ").split(",") if v.strip()]

a = array_body("sobol_a")
minit = array_body("sobol_minit")
assert len(minit) == max_degree * len(a), (len(minit), len(a))

npoly = max_dim - 1
a = a[:npoly]
minit = minit[: max_degree * npoly]

def fmt(vals, per_line=16):
    lines = []
    for i in range(0, len(vals), per_line):
        lines.append("  " + ",".join(str(v) for v in vals[i : i + per_line]) + ",")
    return "\n".join(lines)

out = Path(__file__).resolve().parent.parent / "include" / "nested_sampler" / "sobol_table.hpp"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(
    "// Generated by tools/extract_sobol_table.py. Do not edit by hand.\n"
    "//\n"
    "// Primitive polynomials and initial direction numbers for Sobol sequences,\n"
    "// from S. Joe and F. Y. Kuo, SIAM J. Sci. Comput. 30, 2635-2654 (2008)\n"
    "// (file new-joe-kuo-6.21201), as shipped in boost/random/detail/sobol_table.hpp\n"
    "// (Boost Software License 1.0), truncated to " + str(max_dim) + " dimensions.\n"
    "\n"
    "#ifndef NESTED_SAMPLER_SOBOL_TABLE_HPP\n"
    "#define NESTED_SAMPLER_SOBOL_TABLE_HPP\n"
    "\n"
    "namespace ns {\n"
    "namespace sobol_table {\n"
    "\n"
    "static const unsigned max_dimension = " + str(max_dim) + ";\n"
    "static const unsigned num_polynomials = max_dimension - 1;\n"
    "static const unsigned max_degree = " + str(max_degree) + ";\n"
    "\n"
    "// Primitive binary polynomial for dimension d+1 (d = 0..num_polynomials-1).\n"
    "static const unsigned short polynomial[num_polynomials] = {\n" + fmt(a) + "\n};\n"
    "\n"
    "// Initial direction numbers m_k for dimension d+1: minit[max_degree*d + k].\n"
    "static const unsigned short minit[max_degree * num_polynomials] = {\n" + fmt(minit) + "\n};\n"
    "\n"
    "} // namespace sobol_table\n"
    "} // namespace ns\n"
    "\n"
    "#endif\n"
)
print("wrote", out, "dims", max_dim)
